{- Chris Johnson
 - 2008
 -
 - Problem 2
 - Each new term in the Fibonacci sequence is generated by adding the previous
 - two terms. By starting with 1 and 2, the first 10 terms will be:
 -
 - 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 -
 - Find the sum of all the even-valued terms in the sequence which do not
 - exceed four million.
 -}

prob2 = sum [f | f <- takeWhile (<4000000) fibs, even f]

-- fibs : produce list of Fibonnacci numbers
fibs :: [Integer]
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
